site_name: TerraME 




theme: 
  name: readthedocs
  custom_dir: overrides
  logo: img/terramee.png
  site_favicon: img/favicon.ico
  highlightjs: true

  


nav:
  - ðŸš€ Introduction: 
    - 'index.md'
  


  
markdown_extensions:
  
  #pymdown
  - pymdownx.tasklist # Lista de tarefas
  - pymdownx.emoji # Emojis
  - pymdownx.mark # MarcaÃ§Ãµes
  - pymdownx.tilde # Tachado
  - pymdownx.highlight # cÃ³digo
  - pymdownx.superfences #bloquinho


copyright: Copyright &copy; 2023 TerraME